### ISSUE TITLE
TypeError: cannot convert 'NoneType' object to bytes

### ISSUE THREAD

**Issue by AeroKingdom** [conqp/mcipc#29]
Hello, I am trying to call `stats()` but I am getting this error.
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\James\AppData\Local\Programs\Python\Python39\lib\site-packages\mcipc\query\client.py", line 97, in stats
    file.write(bytes(request))
  File "C:\Users\James\AppData\Local\Programs\Python\Python39\lib\site-packages\mcipc\query\proto\basic_stats.py", line 33, in __bytes__
    payload += bytes(self.challenge_token)
TypeError: cannot convert 'NoneType' object to bytes
```
If it helps, I am trying to pull information from `mc.hypixel.net`.
Any help would be appreciated.

**Comment by conqp** [comment]
Please provide the code that produces the given stacktrace.

**Comment by AeroKingdom** [comment]
```
from mcipc.query import Client

srv = Client('mc.hypixel.net', 25565)
print(srv.stats())
```

**Comment by conqp** [comment]
That's what I suspected. You need to connect to the server first, either by using the context manager capability of the client or by manually calling connect. Please refer to the documentation on proper usage of this library.
