### ISSUE TITLE
Doesn't work anymore

### ISSUE THREAD

**Issue by MeesMeijer** [conqp/mcipc#31]
The module doesn't work on wind 10 or ubuntu, it always gives me timeout error. On websites dedicated to this link["mcstats.io"] it works.

**Comment by conqp** [comment]
As always, please provide the entire code with the entire error message that it produces.
Please also provide the version of mcipc you are using.

**Comment by MeesMeijer** [comment]
error: 
```bash 
Traceback (most recent call last):
  File "C:\Users\meesr\AppData\Local\Programs\Python\Python39\lib\site-packages\mcipc\query\client.py", line 59, in __enter__
    self.connect()
  File "C:\Users\meesr\AppData\Local\Programs\Python\Python39\lib\site-packages\mcipc\query\client.py", line 50, in connect
    self.challenge_token = self.handshake()
  File "C:\Users\meesr\AppData\Local\Programs\Python\Python39\lib\site-packages\mcipc\query\client.py", line 97, in handshake
    response = Response.read(file)
  File "C:\Users\meesr\AppData\Local\Programs\Python\Python39\lib\site-packages\mcipc\query\proto\handshake.py", line 47, in read
    type_ = Type.read(file)
  File "C:\Users\meesr\AppData\Local\Programs\Python\Python39\lib\site-packages\mcipc\query\proto\common.py", line 100, in read
    return cls.from_bytes(file.read(1))
  File "C:\Users\meesr\AppData\Local\Programs\Python\Python39\lib\socket.py", line 704, in readinto
    return self._sock.recv_into(b)
socket.timeout: timed out
```

version: 2.3.3

**Comment by conqp** [comment]
With the partial information that you have provided - I still don't know the code that produces it - all I can assume is, that mcipc works perfectly fine and the remote host, i.e. the server, just lets the connection time out.
This is most likely to administrative settings of the target query server or the server's firewall.

**Comment by MeesMeijer** [comment]
That is strange because with all other options (sites) it just works. This problem started when I upgraded all my modules.
I know it's not my server

**Comment by conqp** [comment]
Well, I just tried it with my own servers and I can get the Query information without any issues.
As long as we cannot rule the more likely issue on the server side, there's nothing that I can do.
