### ISSUE TITLE
An existing connection was forcibly closed by the remote host

### ISSUE THREAD

**Issue by martinohanlon** [conqp/mcipc#45]
I am trying to get mcipc communicating with a vanilla minecraft server.

When running the example program for mcipc I get an `[WinError 10054] An existing connection was forcibly closed by the remote host` error however I dont experience any errors when using `rcon` directly.

This is the example mcipc program I am using:

```
from mcipc.query import Client

with Client('127.0.0.1', 25565) as client:
    basic_stats = client.stats()            # Get basic stats.
    full_stats = client.stats(full=True)    # Get full stats.

print(basic_stats)
print(full_stats)
```

.. which generates this error and I dont see any notifications in the server console.

```
Traceback (most recent call last):
  File "C:\Users\marti\Documents\martinohanlon\rcon-test-env\rcontests\mcipc-test.py", line 3, in <module>
    with Client('127.0.0.1', 25565) as client:
  File "C:\Users\marti\Documents\martinohanlon\rcon-test-env\lib\site-packages\mcipc\query\client.py", line 59, in __enter__
    self.connect()
  File "C:\Users\marti\Documents\martinohanlon\rcon-test-env\lib\site-packages\mcipc\query\client.py", line 50, in connect
    self.challenge_token = self.handshake()
  File "C:\Users\marti\Documents\martinohanlon\rcon-test-env\lib\site-packages\mcipc\query\client.py", line 97, in handshake
    response = Response.read(file)
  File "C:\Users\marti\Documents\martinohanlon\rcon-test-env\lib\site-packages\mcipc\query\proto\handshake.py", line 47, in read
    type_ = Type.read(file)
  File "C:\Users\marti\Documents\martinohanlon\rcon-test-env\lib\site-packages\mcipc\query\proto\common.py", line 101, in read
    return cls.from_bytes(file.read(1))
  File "C:\Users\marti\AppData\Local\Programs\Python\Python310\lib\socket.py", line 705, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host
```

I created a simple program using rcon to check everything was running correctly.

```
from rcon.source import Client

with Client('127.0.0.1', 25575, passwd='letme1n') as client:
    response = client.run('say', 'hi')

print(response)
```

... which runs without error and generates the following result in the server console.

```
[15:18:58] [RCON Listener #1/INFO]: Thread RCON Client /127.0.0.1 started
[15:18:58] [Server thread/INFO]: [Not Secure] [Rcon] hi
[15:18:58] [RCON Client /127.0.0.1 #2/INFO]: Thread RCON Client /127.0.0.1 shutting down
```

I didnt know if there was a way of specifying the password for mcipc? but as far as I can tell the connection is being made anyway?!

Any advice would be greatly received.

**Comment by conqp** [comment]
Your ports differ in your two examples.

**Comment by martinohanlon** [comment]
>Did you enable QUERY on your MC server?

Probably not, I wasn't aware I had too.

I will take a look, thanks for getting back to me.

**Comment by martinohanlon** [comment]
Yes, that did the trick. Thank you.
