### ISSUE TITLE
[query] full_stats throws OverflowError

### ISSUE THREAD

**Issue by Itzdvbravo** [conqp/mcipc#5]
```
Ignoring exception in on_command_error
Traceback (most recent call last):
  File "C:\Users\prave\AppData\Local\Programs\Python\Python38-32\lib\site-packages\discord\ext\commands\core.py", line 83, in wrapped
    ret = await coro(*args, **kwargs)
  File "c:\Users\prave\Desktop\Codest\Python\MSC\SerenityBot.py", line 280, in mctest2
    full_stats = client.full_stats
  File "C:\Users\prave\AppData\Local\Programs\Python\Python38-32\lib\site-packages\mcipc\query\proto\full_stats.py", line 177, in full_stats
    return self.communicate(request, FullStats)
  File "C:\Users\prave\AppData\Local\Programs\Python\Python38-32\lib\site-packages\mcipc\query\client.py", line 48, in communicate  
    self._socket.send(bytes(packet))
  File "C:\Users\prave\AppData\Local\Programs\Python\Python38-32\lib\site-packages\mcipc\query\proto\full_stats.py", line 107, in __bytes__
    payload += self.challenge_token.to_bytes(4, 'big')
OverflowError: can't convert negative int to unsigned

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\prave\AppData\Local\Programs\Python\Python38-32\lib\site-packages\discord\client.py", line 312, in _run_event      
    await coro(*args, **kwargs)
  File "c:\Users\prave\Desktop\Codest\Python\MSC\SerenityBot.py", line 50, in on_command_error
    raise error
  File "C:\Users\prave\AppData\Local\Programs\Python\Python38-32\lib\site-packages\discord\ext\commands\bot.py", line 892, in invoke
    await ctx.command.invoke(ctx)
  File "C:\Users\prave\AppData\Local\Programs\Python\Python38-32\lib\site-packages\discord\ext\commands\core.py", line 797, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "C:\Users\prave\AppData\Local\Programs\Python\Python38-32\lib\site-packages\discord\ext\commands\core.py", line 92, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: OverflowError: can't convert negative int to unsigned
```
```
@bot.command()
async def mctest2(ctx):
    with Client(ip, port) as client:
        full_stats = client.full_stats
    await ctx.send(full_stats)
```

Fix this issue please, i like this lib, basic_stats working fine but not this one

**Comment by conqp** [comment]
A vanilla server should never return a negative challenge token.
What Minecraft version are you using?
Please also test whether https://github.com/conqp/mcipc/commit/038839905f44a3a7f21242b21d3fdf821a74310b fixes the issue.

**Comment by Itzdvbravo** [comment]
am using mcpe btw

**Comment by Itzdvbravo** [comment]
and yes it does fix it thx
