### ISSUE TITLE
Always times out

### ISSUE THREAD

**Issue by FightMan01** [conqp/mcipc#9]
I want to implement this to my discord bot, but it's always times out. Here is my base:
```py
    @commands.command()
    async def mcstats(self, ctx, *, ip):
        if ctx.author.bot:
            return
        try:
            port = ip.split(":")[1]
        except:
            port = 25565
        ip = ip.split(":")[0]
        with Client(ip, int(port), timeout=10) as client:
            basic_stats = client.basic_stats
        await ctx.send(basic_stats)
```

Traceback:

```
Traceback (most recent call last):
  File "/Users/nemetharon/Desktop/FightMan01_bot/1.2.3/sql/fun.py", line 1504, in mcstats
    with Client(ip, int(port), timeout=10) as client:
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/mcipc/query/client.py", line 30, in __enter__
    self._challenge_token = self.handshake().challenge_token
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/mcipc/query/proto/handshake.py", line 64, in handshake
    return self.communicate(request, Response)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/mcipc/query/client.py", line 49, in communicate
    response = self._recv_all(buffer=buffer)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/mcipc/query/client.py", line 44, in _recv_all
    return b''.join(self._recv_chunks(buffer=buffer))
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/mcipc/query/client.py", line 36, in _recv_chunks
    while chunk := self._socket.recv(buffer):
socket.timeout: timed out
```

**Comment by conqp** [comment]
The information you provided does not indicate a problem with the `mcipc` library, but rather with your server configuration.

If you want a more detailed answer, please provide the actual values of `ip` and `port` in that scenario and the result of

`
    with Client(ip, int(port), timeout=10) as client:
        basic_stats = client.basic_stats
`
with these values from an interactive python console.

**Comment by FightMan01** [comment]
Thank you for the replay!
I tried with different ips and ports for eg: `play.szalicilmc.hu:49184` , `mc.avalion.hu` , `server20.clans.hu:25602` , `play.themegacrafted.hu` etc..

Some refuses the connection (I can understand it, it's ok) but the others always times out.

**Comment by conqp** [comment]
So, this isn't your server you're trying to connect to.
If some foreign server refuses the connection or lets it time out due to lack of reply, this is an administrative decision by the respective server / firewall operator.
You'll need contact the respective server operators if you want permission to access their servers using the query protocol.

**Comment by FightMan01** [comment]
Oh, ok :(

Thank you for the help.
